[project]
name = "helloLLM"
version = "0.1.0"
description = "A simple Python project to get started with LLM"
readme = "README.md"
requires-python = ">=3.9"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
